env:
  es6: true
  node: true
  mocha: true

extends: "eslint:recommended"

parserOptions:
  sourceType: module

plugins:
  - json

rules:
  curly: "error"
  default-case: "error"
  eqeqeq:
    - "error"
    - "always"
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  max-len:
    - "error"
    -
      code: 120
  no-console: off
  no-global-assign: "error"
  no-magic-numbers: "error"
  no-multi-spaces: "error"
  no-multi-str: "error"
  no-multiple-empty-lines:
    - "error"
    -
      max: 1
  no-trailing-spaces: "error"
  no-unused-labels: "error"
  no-useless-escape: off
  quotes:
    - error
    - single
  semi:
    - error
    - never
  space-infix-ops: "error"
